### ISSUE TITLE
How to verify if the set method worked out?

### ISSUE THREAD

**Issue by Claire-Eleutheriane** [modelon/PyFMI#16]
There seems to be no way of checking if the set method was successful without running the model.
In my case, the FMU I want to run crashes unless very specific values are set. Only, as it crashes, I can not verify if the set method worked out, or if the variables in my FMU are protected.
Is there way to solve this matter?

**Comment by chria** [comment]
If the set method is not successful an exception will be raised. So if you don't get the exception, the FMU accepts the values that you tried to set.

**Comment by Claire-Eleutheriane** [comment]
Hi Christian,


Thanks a lot for your answer. It is very helpful.


Best regards,


Claire-Eleuthèriane



De : Christian Winther <notifications@github.com>
Envoyé : mardi 17 septembre 2019 19:07:40
À : modelon/PyFMI
Cc : Claire-Eleutheriane Gerrer | Phimeca; Author
Objet : Re: [modelon/PyFMI] How to verify if the set method worked out? (#16)
 


If the set method is not successful an exception will be raised. So if you don't get the exception, the FMU accepts the values that you tried to set.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute th e thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/modelon/PyFMI/issues/16?email_source=notifications\u0026email_token=AJVPKYA6FEOJM7NDWJJQARDQKEFFZA5CNFSM4IXPVNI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD65HBTI#issuecomment-532312269",
"url": "https://github.com/modelon/PyFMI/issues/16?email_source=notifications\u0026email_token=AJVPKYA6FEOJM7NDWJJQARDQKEFFZA5CNFSM4IXPVNI2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD65HBTI#issuecomment-532312269",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
