### ISSUE TITLE
[question] get a list of variables for an pyfmi.fmi_algorithm_drivers.FMIResult object

### ISSUE THREAD

**Issue by Foadsf** [modelon/PyFMI#18]
I would have normally asked this question [here on the JModelica forum](https://jmodelica.org/forum), but it is unfortunately down. I'm trying to find the solution to [this question I asked on StackOverflow](https://stackoverflow.com/q/58219336/4999991). I have run a simulation, but when I try to retrieve the data, I get the error message:

> VariableNotFoundError: Cannot find variable ... in data file.

I want to know if/how I can get a list of available variable names in a `pyfmi.fmi_algorithm_drivers.FMIResult` object. According to the source code, `FMIResult` is a subclass of `JMResultBase`, but I don't know how to go further than this. I would appreciate it if you could help me understand what the problem is and how I can solve it. Thanks for your support in advance.

**Comment by chria** [comment]
See https://stackoverflow.com/questions/58219336/cant-retrieve-the-results-back-from-jmodelica-to-python . Closing.
