### ISSUE TITLE
CS2 FMU and execution tool

### ISSUE THREAD

**Issue by jlabroquere** [modelon/PyFMI#2]
Hello,

I need to use PyFMI with co-simulation using a model exported from a software. Unfortunately, when I try to load the FMU file, it raises this error : "Models that need an execution tool are not supported".

What can I do to make it work? Why such a limitation?

Best regards.

**Comment by toivoh** [comment]
Answered here: http://www.jmodelica.org/27626#comment-6290

**Comment by xjysb** [comment]
Hello，

I have the same problem!
Since the website "http://www.jmodelica.org/27626#comment-6290" is no longer avaliable, where can I see the answer?

Best regards.

**Comment by kosmylo** [comment]
Any idea for the solution to this issue?
