### ISSUE TITLE
Segmentation Fault when estimating parameters (sometimes)

### ISSUE THREAD

**Issue by lukedempsey** [modelon/PyFMI#7]
Just want to preface this by saying that I know this isn't the place for issues to be logged, but jmodelica.com is down and I don't really know if this is a usual thing as I only just jumped on board last week.

I'm doing a parameter estimation for an FMU which I generated with OpenModelica. If I run a large enough estimation (long simulation duration or numerous params to be simulated), I will encounter a segfault.

I have attached the relevant part of my python script calling the estimation. 
I ran the script inside gdb and printed out a backtrace of the fault, also below.

Any ideas of what I can do to fix this?

Edit: I forgot to add that this is on a VM, I'll rebuild this on a non-VM and see if it's related to that.

estimation.py:
```
# gather simulated data
t_meas = res['time']
u_meas = res['u']
y_meas = res['y']

meas_data = np.vstack((t_meas, y_meas)).transpose()
input_data = np.vstack((t_meas, u_meas)).transpose()

# change the parameters to be estimated so that there is an error

# model = load_fmu(args.filepath)
model.set('springDamper1.d', 0.2)
model.set('springDamper1.d', 0.2)

#Run Estimation
est_opts = model.estimate_options()
est_opts["tolerance"] = 1e-6
res_est = model.estimate(options=est_opts, parameters=['springDamper1.c','springDamper1.d'], measurements=(['y'], meas_data), input=(['u'], input_data))
res_est_sim = model.simulate(final_time=5, input=input_object, options=opts)
```

GDB backtrace:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffd862fbdf in pool_malloc.lto_priv ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
(gdb) Quit
(gdb) bt
#0  0x00007fffd862fbdf in pool_malloc.lto_priv ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#1  0x00007fffd86422b2 in mmc_mk_scon.lto_priv ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#2  0x00007fffd8631167 in modelica_string_format_to_c_string_format ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#3  0x00007fffd8631180 in modelica_real_to_modelica_string_format ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#4  0x00007fffd863cdcd in Test_eqFunction_49 ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#5  0x00007fffd863d2c2 in Test_updateBoundParameters ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#6  0x00007fffd86461ae in initialization ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#7  0x00007fffd863eace in fmi2EnterInitializationMode ()
   from /tmp/luke/JModelica.org/jm_tmpjW_YQw/binaries/linux64/Test.so
#8  0x00007fffe4122b4e in __pyx_pf_5pyfmi_3fmi_13FMUModelBase2_34enter_initialization_mode (__pyx_v_self=0x5555570b8300) at src/pyfmi/fmi.c:46575
#9  __pyx_pw_5pyfmi_3fmi_13FMUModelBase2_35enter_initialization_mode (
    __pyx_v_self=0x5555570b8300, unused=<optimised out>)
    at src/pyfmi/fmi.c:46512
#10 0x00007fffe4067a30 in __Pyx_PyObject_CallMethO (arg=0x0, 
    func=0x7fffd3f047a0) at src/pyfmi/fmi.c:96058
```

Dependencies:
* Python 2.7.15rc1 (x64)
* Sundials 2.4.0 (could not install 2.6 as it changed to CMAKE and I could not link the sundials_config.h file (http://sundials.2283335.n4.nabble.com/Installation-Issues-td4653808.html)
* Assimulo 2.9 (installed without BLAS or LAPACK)
* FMILibrary 2.3.1

**Comment by chria** [comment]
Hi,

Looking at the stacktrace it seems like there is a memory issue within the FMU. During the estimation, do you run out of available memory on your machine? 

From what I can see the issue comes from within the FMU so I'd recommend to get in contact with OpenModelica and see if they have any known memory issues with their FMUs. Have you tried to generate the FMU using another tool and see if the same issue comes up?

Best
/Christian

**Comment by lukedempsey** [comment]
Hi Christian,

I've raised a ticket with OpenModelica (https://trac.openmodelica.org/OpenModelica/ticket/5102), I'll let you know how it goes.

Thanks,
Luke

**Comment by lukedempsey** [comment]
Update: Was a known issue in OpenModelica, just had to wait for the next nightly build.

Thanks for your help Christian
